### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by chuvak889** [Undeadkillz/node-steam-bot-manager#45]
e:\node_modules\node-steam-bot-manager\lib\index.js:119
    if (self.config.hasOwnProperty("api_port") && self.config.api_port != null) {
                    ^

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at BotManager.startWebserver (e:\node_modules\node-steam-bot-manager\lib\index.js:119:21)
    at BotManager.startManager (e:\node_modules\node-steam-bot-manager\lib\index.js:173:10)
    at new VoteBot (e:\VoteBot.js:73:17)
    at Object.<anonymous> (e:\VoteBot.js:79:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by SamerAlsayegh** [comment]
Hey there,

I haven't worked on this project in a few years however your issue seems to be same as #43,
You will need to manually create the config.json file with the following details;

https://pastebin.com/46zLY3AW

It should work then, but I also don't know if the wrapper still works as intended. So just beware of that.

**Comment by chuvak889** [comment]
> Hey there,
> 
> I haven't worked on this project in a few years however your issue seems to be same as #43,
> You will need to manually create the config.json file with the following details;
> 
> https://pastebin.com/46zLY3AW
> 
> It should work then, but I also don't know if the wrapper still works as intended. So just beware of that.

Thank you very much for answering me. I will try it! 
Have a nice day
