### ISSUE TITLE
Problem with Start API.

### ISSUE THREAD

**Issue by radekp00** [Undeadkillz/node-steam-bot-manager#6]
Hello, I have problem when I try to start APITradebot.js. It's my log:
`2017-04-25T13:51:42.030Z - debug: Starting Bot Manager
2017-04-25T13:51:42.033Z - debug: Loaded config
2017-04-25T13:51:42.083Z - error: Failed to read account data - check file for any malformation using a JSON parser
2017-04-25T13:51:42.105Z - error:  TypeError: botsManager.addEndpoint is not a function
    at D:\bot\examples\InventoryBot.js:54:21
    at D:\bot\node_modules\node-steam-bot-manager\index.js:73:17
    at D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:76:21
    at D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:147:13
    at DataControl.getFile (D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:113:9)
    at DataControl.loadAccounts (D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:138:10)
    at D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:71:18
    at DataControl.validateConfig (D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:105:5)
    at D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:159:18
    at DataControl.getFile (D:\bot\node_modules\node-steam-bot-manager\components\DataControl.js:113:9)
2017-04-25T13:51:42.109Z - error: Error initializing data - TypeError: botsManager.addEndpoint is not a function
2017-04-25T13:51:42.112Z - error: Failed to start Bot Manager
2017-04-25T13:51:42.693Z - debug: Logged on to chat on "12_98"
2017-04-25T13:51:42.695Z - debug: Logged into "12_98"
`

**Comment by radekp00** [comment]
Yery sorry for creating this issue. I run this on windows and I not run this as administrator.
